### ISSUE TITLE
NumberAdapter Error

### ISSUE THREAD

**Issue by Souls362** [diqiuzhuanzhuan/poros#2]
```
input is 五亿零五十五万五千, expect is 500555000, actually is 500055050.0
Traceback (most recent call last):
  File "/home/frankqi/Desktop/poros/poros/poros_chars/chinese_to_arabic.py", line 142, in <module>
    assert(NumberAdapter.convert(ele[0]) == ele[1])
AssertionError
```
Can you fix this?

**Comment by diqiuzhuanzhuan** [comment]
> ```
> input is 五亿零五十五万五千, expect is 500555000, actually is 500055050.0
> Traceback (most recent call last):
>   File "/home/frankqi/Desktop/poros/poros/poros_chars/chinese_to_arabic.py", line 142, in <module>
>     assert(NumberAdapter.convert(ele[0]) == ele[1])
> AssertionError
> ```
> 
> Can you fix this?
I will fix it, 3q!

**Comment by diqiuzhuanzhuan** [comment]
I have fixed it! Thank you!
